import type { DataSource, ResearchPurpose } from "./types";

const enc = (s: string) => encodeURIComponent(s);

export function buildSources(query: string, purpose: ResearchPurpose): Record<string, DataSource[]> {
  const q = enc(query);
  const qPlain = enc(query.replace(/\s+/g, ""));

  const all: DataSource[] = [
    // ── 자동 수집 (실데이터) ──
    {
      id: "dart",
      title: "DART 전자공시",
      emoji: "📑",
      category: "auto",
      description: "금융감독원 — 상장·외감 대상 기업 사업보고서, 분기보고서, 주요사항 자동 조회",
      checklist: [
        "사업보고서 (직전 3개년) 매출 · 영업이익 · 당기순이익",
        "재무상태표 (자산 · 부채 · 자본)",
        "현금흐름표 (영업/투자/재무)",
        "주요 지배구조 · 주주 현황",
      ],
      url: `https://dart.fss.or.kr/dsab007/main.do?textCrpNm=${q}`,
    },
    {
      id: "naver_news",
      title: "네이버 뉴스",
      emoji: "📰",
      category: "auto",
      description: "최근 8건 자동 수집 (최신순) — 본문 요약 포함",
      checklist: ["기업 동향 · IR · 임원진 변화", "신제품 출시 · 라인업 확장", "수상/인증/제휴 보도자료"],
      url: `https://search.naver.com/search.naver?where=news&query=${q}`,
    },
    {
      id: "naver_shopping",
      title: "네이버 쇼핑",
      emoji: "🛒",
      category: "auto",
      description: "노출 상품 가격대 · 판매처 · 카테고리 — 12개 카드 자동 수집",
      checklist: ["판매처 분포 (자사몰 vs 오픈마켓 vs 종합몰)", "가격 포지셔닝", "상위 노출 SKU 라인업"],
      url: `https://search.shopping.naver.com/search/all?query=${q}`,
    },
    {
      id: "naver_blog",
      title: "네이버 블로그",
      emoji: "✍️",
      category: "auto",
      description: "최근 후기 · 인플루언서 콘텐츠 6건 자동 수집",
      checklist: ["진성 후기 vs 협찬", "인플루언서 노출량", "브랜드 톤 · 컨셉 인식"],
      url: `https://search.naver.com/search.naver?where=post&query=${q}`,
    },

    // ── 외부 (1클릭 검색) ──
    {
      id: "thevc",
      title: "THE VC",
      emoji: "🏦",
      category: "external",
      description: "투자유치 이력 · 누적 펀딩액 · 투자자 · 라운드별 밸류에이션",
      checklist: ["Series 라운드별 투자금/투자자/일자", "누적 펀딩 규모", "리드 투자자 · 후속 투자 가능성"],
      url: `https://thevc.kr/search?q=${q}`,
      priority: purpose === "investment" || purpose === "ma" ? 1 : 3,
    },
    {
      id: "innoforest",
      title: "혁신의숲",
      emoji: "🌳",
      category: "external",
      description: "스타트업 데이터 · 성장지표 · 트래픽/매출 추이 · 기업 비교",
      checklist: ["월 매출 추이 (추정)", "앱/웹 트래픽 트렌드", "동종업계 비교 지표"],
      url: `https://www.innoforest.co.kr/search?keyword=${q}`,
      priority: purpose === "investment" || purpose === "ma" ? 1 : 2,
    },
    {
      id: "venture_confirm",
      title: "벤처확인 공시",
      emoji: "🛡️",
      category: "external",
      description: "벤처기업 확인 여부 · 인증 종류 · 유효기간 (벤처기업종합관리시스템)",
      checklist: ["벤처기업 확인 여부", "벤처 유형 (벤처투자/연구개발/혁신성장)", "유효기간 · 갱신 여부"],
      url: `https://www.smes.go.kr/venturein/pbntc/searchVntrCmpAction?searchKeyword=${q}`,
      priority: purpose === "investment" ? 2 : 4,
    },
    {
      id: "kbiz_status",
      title: "중소기업현황정보시스템",
      emoji: "🏭",
      category: "external",
      description: "중소기업 확인서 · 매출규모 · 종업원 수 · 업종 분류",
      checklist: ["중소기업 vs 중견기업 분류", "공시 매출 규모", "주요 업종 코드"],
      url: `https://sminfo.mss.go.kr/cm/sv/CSV001R0.do?searchKeyword=${q}`,
      priority: 3,
    },
    {
      id: "saramin",
      title: "사람인 채용공고",
      emoji: "👔",
      category: "external",
      description: "현재 모집중 채용공고 수 → 조직 확장 시그널",
      checklist: ["채용 공고 수 (전체/직군별)", "신규 직군 모집 (사업확장 신호)", "연봉 공개 정보"],
      url: `https://www.saramin.co.kr/zf_user/search?searchword=${q}`,
      priority: purpose === "investment" ? 2 : 3,
    },
    {
      id: "jobkorea",
      title: "잡코리아",
      emoji: "💼",
      category: "external",
      description: "기업 리뷰 · 평균연봉 · 면접후기 → 조직 평판",
      checklist: ["전·현직자 평점 (5점 만점)", "장단점 키워드", "면접 난이도/방식"],
      url: `https://www.jobkorea.co.kr/Search/?stext=${q}`,
      priority: purpose === "investment" || purpose === "ma" ? 2 : 3,
    },
    {
      id: "jobplanet",
      title: "잡플래닛",
      emoji: "🪐",
      category: "external",
      description: "직원 평가 · 복지/워라밸/CEO 만족도",
      checklist: ["총괄 평점", "CEO 지지율", "워라밸·승진·복지 영역별 점수"],
      url: `https://www.jobplanet.co.kr/search?query=${q}&category=companies`,
      priority: purpose === "ma" ? 2 : 3,
    },
    {
      id: "ftc_ecommerce",
      title: "공정위 통신판매사업자",
      emoji: "🏛️",
      category: "external",
      description: "통신판매업 신고 · 사업자등록번호 · 대표자 · 신고기관",
      checklist: ["통신판매업 신고번호", "신고 관할 지자체", "대표자 · 사업장 주소 일치 여부"],
      url: `https://www.ftc.go.kr/bizCommPop.do?wrkr_no=&apv_perm_no=&query=${q}`,
      priority: purpose === "sourcing" ? 1 : 3,
    },
    {
      id: "google",
      title: "Google 검색",
      emoji: "🔍",
      category: "external",
      description: "글로벌 노출 · 영문 미디어 · 해외 시장 평가",
      checklist: ["글로벌 미디어 인용", "공식 영문 사이트", "해외 진출 보도"],
      url: `https://www.google.com/search?q=${q}`,
    },
    {
      id: "crunchbase",
      title: "Crunchbase",
      emoji: "🌐",
      category: "external",
      description: "글로벌 스타트업 DB · 영문 회사 정보 (해외 진출 시)",
      checklist: ["Total Funding", "Investor 명단 (해외 VC)", "Founders / Key People"],
      url: `https://www.crunchbase.com/textsearch?q=${q}`,
      priority: purpose === "investment" || purpose === "ma" ? 2 : 4,
    },
    {
      id: "instagram",
      title: "인스타그램",
      emoji: "📷",
      category: "external",
      description: "공식계정 팔로워 · 해시태그 게시물 수 → 브랜드 영향력",
      checklist: ["공식 계정 팔로워 수", "해시태그 게시물 수", "Reels 평균 조회수"],
      url: `https://www.instagram.com/explore/tags/${qPlain}/`,
      priority: purpose === "jbp" || purpose === "sourcing" ? 1 : 3,
    },
    {
      id: "youtube",
      title: "YouTube 리뷰",
      emoji: "🎬",
      category: "external",
      description: "유튜브 리뷰/광고 노출 → 인플루언서 마케팅 강도",
      checklist: ["인플루언서 협찬 영상", "리뷰 평균 조회수", "광고 캠페인 형태"],
      url: `https://www.youtube.com/results?search_query=${enc(query + " 후기")}`,
      priority: purpose === "jbp" ? 1 : 3,
    },
    {
      id: "oliveyoung",
      title: "올리브영",
      emoji: "🌿",
      category: "external",
      description: "올영 입점 여부 · 카테고리 랭킹 · 리뷰 수",
      checklist: ["입점 여부", "카테고리별 랭킹", "리뷰 평점 · 건수"],
      url: `https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=${q}`,
      priority: purpose === "jbp" || purpose === "sourcing" ? 1 : 3,
    },
    {
      id: "coupang",
      title: "쿠팡",
      emoji: "📦",
      category: "external",
      description: "쿠팡 입점 · 가격대 · 로켓배송 여부",
      checklist: ["로켓배송 입점 여부", "최저가 vs 자사몰 가격", "Q&A·리뷰 흐름"],
      url: `https://www.coupang.com/np/search?q=${q}`,
      priority: purpose === "jbp" ? 2 : 3,
    },
    {
      id: "amazon_us",
      title: "Amazon US",
      emoji: "🇺🇸",
      category: "external",
      description: "북미 직진출 · BSR · 별점 · 리뷰량",
      checklist: ["Best Seller Rank (BSR)", "리뷰 수 · 평점", "FBA 여부"],
      url: `https://www.amazon.com/s?k=${q}`,
      priority: purpose === "investment" || purpose === "jbp" ? 2 : 4,
    },
    {
      id: "sephora",
      title: "Sephora",
      emoji: "💄",
      category: "external",
      description: "글로벌 럭셔리/K뷰티 진출 — Sephora US/EU",
      checklist: ["Sephora 입점 여부", "별점 · 리뷰", "Sephora Collection 협업"],
      url: `https://www.sephora.com/search?keyword=${q}`,
      priority: purpose === "jbp" ? 2 : 4,
    },
  ];

  // 목적별 가중치 정렬
  const sortByPriority = (a: DataSource, b: DataSource) =>
    (a.priority ?? 5) - (b.priority ?? 5);

  return {
    auto: all.filter((s) => s.category === "auto"),
    external: all.filter((s) => s.category === "external").sort(sortByPriority),
  };
}
